### ISSUE TITLE
`make init` doesn't match ARC's guidelines

### ISSUE THREAD

**Issue by mdj2** [PSU-OIT-ARC/team_dynamics#11]
(because this project got started before we had guidelines)

> make init is the most important make target. It should do everything required to go from a `git clone` to actually running the app. It is assumed the user is running this command on the offical ARC vagrant box. In the Django world, this target should create a virtualenv, pip install any required packages, create a database, run migrations, collectstatic files, download any necessary binaries (like ffmpeg), and load up initial data.

> It is good to generate some dummy data so the user doesn't have to. And it's nice if you generate an administrative user for them too.

> This operation should be idempotent. This makes the operation dangerous, because it will have to DROP the database if it exists, for example.

**Comment by ssean1** [comment]
Refactored makefile incoming

**Comment by mdj2** [comment]
#13 resolves this
